### ISSUE TITLE
Wildcard Cert Request

### ISSUE THREAD

**Issue by bgbearcatfan** [jpconver/dnsexit_dnshook#2]
Thanks for this project.  Works very well.  Curious if there is any plan to make this work for wildcard requests?  Currently receive this error message:

Failed authorization procedure. mydomain.com (dns-01): urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking                                                                                                                         up TXT for _acme-challenge.mydomain.com

**Comment by frederickjh** [comment]
@bgbearcatfan I am using this hook for dns wildcard requests. However I found that if you are trying to use it to create a wildcard for a subdomain it was not handle correctly see #1 for information on how I fixed this.

I should also add that I am here in the issue because the plugin stopped working as it could not parse the HTML on the DNSexit.com website. I fixed this in my fork of this project in this [commit](https://github.com/topdroplabs/dnsexit_dnshook/commit/1c10123ec2da20c892e3adce3b7e68219608fce7).
I did it in my fork as I am not familiar with python regex that were used in the original code, so I used [ericchiang/pup](https://github.com/ericchiang/pup) that I do know.

**Comment by bgbearcatfan** [comment]
Thanks for reaching out.  I actually figured out the wildcard issue a while back.

I also started having issues with the plugin not working anymore.  I tried your changes, but still the same issue, as the TXT records never get edited/saved to DNSexit.  I'll keep messing with your fork, as it seems the original creator is no longer active.

**Comment by frederickjh** [comment]
@bgbearcatfan Have you checked while it is running that the DNS record is being created?

Also, related to my version do you have [pup](https://github.com/ericchiang/pup) installed? Can you run it from anywhere? Is it in your **$PATH** so the script can call it too?

**Comment by frederickjh** [comment]
@bgbearcatfan Also if you are trying to create a wildcard for a subdomain, have you seen my fix for that in #1 ?

**Comment by bgbearcatfan** [comment]
Yeah, i even inserted a couple pauses after the saving txt entry piece, and nothing.  So i went back to the old script and took another look.  I was actually able to make it work by editing the authenticator.sh script.  I disabled/commented the line "get dnsexit domain" and at the top edited "basedomain=" to be hard coded to my domain name.  So basically getting rid of the base.sh script fixed all my issues.  

All that being said, i think i would still like to try getting your config working.  It's nice to find an active dnsexit user to collab with!

**Comment by frederickjh** [comment]
You could try debugging the `base.sh` script by adding these lines to the top after the hash bang:
```bash
#!/bin/bash
# For testing. First line outputs line numbers.
# Second line says to output what is going on in script
PS4=':${LINENO}+'
set -x
```
This will print out each line in the script with the line number before running them.
To turn off debugging comment out the line `set -x`.

**Comment by jpconver** [comment]
Hi! I added some commits. I think this issue is fixed... :)

**Comment by frederickjh** [comment]
@jpconver Thanks for working on that. I replaced my fork with your new version and at first it did not  work to get a wildcard certificate. 

However, that is related to my situation and not your code. I found I added a hack to get around this in my fork. I have dnsmasq forwarding all requests for the wildcard domain to an internal server so the dig query will never return a result. I realize now that instead of my hack I could have added an option to specify the DNS server to query and this would have also solved this. I added `@1.1.1.1` to the dig line in `authenticator.sh` and it was able to get a new wildcard certificate.

I forked this repository back in 2018 because I thought it was abandoned and I hacked it. I have made a number of changes to the repository. Everything from file permissions that have to be changed after cloning, .gitignore file, documentation, and code fixes. If you are interested I can start to pick these from my repository and make pull requests against this one. Just let me know. You can checkout my [commits](https://github.com/topdroplabs/dnsexit_dnshook/commits/master) over on my fork.

As to the original issue you can close it as solved.
